// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbpj5iEJDKiY8x_TFlNGi4IMz88mXgRAw',
    appId: '1:144887236542:web:524f345ba1089d386e5bef',
    messagingSenderId: '144887236542',
    projectId: 'fyppaperlessexam-fdccd',
    authDomain: 'fyppaperlessexam-fdccd.firebaseapp.com',
    storageBucket: 'fyppaperlessexam-fdccd.firebasestorage.app',
    measurementId: 'G-8FXLGBTCMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjh4pHF8ZHOctIoVqq5q2A7RcNiuNEaUA',
    appId: '1:144887236542:android:307c67b7331b46b06e5bef',
    messagingSenderId: '144887236542',
    projectId: 'fyppaperlessexam-fdccd',
    storageBucket: 'fyppaperlessexam-fdccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-nzxFZD-GFOV-60KivKDA9ZfzzPzCb_8',
    appId: '1:144887236542:ios:4960447e76c1b5e26e5bef',
    messagingSenderId: '144887236542',
    projectId: 'fyppaperlessexam-fdccd',
    storageBucket: 'fyppaperlessexam-fdccd.firebasestorage.app',
    iosBundleId: 'com.example.fyppaperless',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbpj5iEJDKiY8x_TFlNGi4IMz88mXgRAw',
    appId: '1:144887236542:web:e6624b5e698a83c26e5bef',
    messagingSenderId: '144887236542',
    projectId: 'fyppaperlessexam-fdccd',
    authDomain: 'fyppaperlessexam-fdccd.firebaseapp.com',
    storageBucket: 'fyppaperlessexam-fdccd.firebasestorage.app',
    measurementId: 'G-S6ZGPZ8CGY',
  );
}
